phobia_list = ["Achluophobia ", "Acousticophobia ",
"Acrophobia ",
"Aerophobia ",
"Agoraphobia ",
"Agyrophobia ",
"Aichmophobia ",
"Ailurophobia ",
"Algophobia ",
"Ancraophobia ",
"Aquaphobia ",
"Arachnophobia ",
"Astraphobia ",
"Autophobia ",
"Bacteriophobia ",
"Basophobia ",
"Batrachophobia ",
"Belonephobia ",
"Bibliophobia ",
"Cacophobia ",
"Carcinophobia ",
"Catoptrophobia ",
"Chemophobia ",
"Cherophobia ",
"Chiroptophobia ",
"Chromophobia ",
"Chronomentrophobia ",
"Chronophobia ",
"Cibophobia ",
"Claustrophobia ",
"Coimetrophobia ",
"Coulrophobia ",
"Cyberphobia ",
"Cynophobia ",
"Demonophobia ",
"Dendrophobia ",
"Dentophobia ",
"Domatophobia ",
"Emetophobia ",
"Enochlophobia ",
"Entomophobia ",
"Ephebiphobia ",
"Equinophobia ",
"Ergophobia ",
"Frigophobia ",
"Gamophobia ",
"Gephyrophobia ",
"Gerascophobia ",
"Germophobia ",
"Globophobia ",
"Glossophobia ",
"Halitophobia ",
"Heliophobia ",
"Helminthophobia ",
"Hemophobia ",
"Herpetophobia ",
"Hexakosioihexekontahexaphobia ",
"Hodophobia ",
"Hydrophobia ",
"Hypochondria ",
"Ichthyophobia ",
"Insectophobia ",
"Koumpounophobia ",
"Lepidopterophobia ",
"Lilapsophobia ",
"Mageirocophobia ",
"Melanophobia ",
"Melissophobia ",
"Monophobia ",
"Musophobi ",
"Myrmecophobia ",
"Necrophobia ",
"Neophobia ",
"Noctiphobia ",
"Nosocomephobia ",
"Numerophobia ",
"Nyctophobia ",
"Obesophobia ",
"Ommetaphobia ",
"Oneirophobia ",
"Ophidiophobia ",
"Ornithophobia ",
"Osmophobia ",
"Ostraconophobia ",
"Panphobia ",
"pediaphobia ",
"Pharmacophobia ",
"Phasmophobia ",
"Phobophobia ",
"Phonophobia ",
"Pogonophobia ",
"Porphyrophobia ",
"Pteromerhanophobia ",
"Pyrophobia ",
"Radiophobia ",
"Roller coaster phobia ",
"Siderodromophobia ",
"Sociophobia ",
"Somniphobia ",
"Taphophobia ",
"Technophobia ",
"Tetraphobia ",
"Thalassophobia ",
"Thanatophobia ",
"Thermophobia ",
"Toxiphobia ",
"Traumatophobia ",
"Trichophobia ",
"Triskaidekaphobia ",
"Trypanophobia ",
"Vehophobia ",
"Xanthophobia ",
"Xenophobia ",
]

fear_name_list = ["darkness",
"noise",
"heights",
"flying",
"open spaces",
"crossing streets",
"sharp objects",
"cats",
"pain",
"wind",
"water",
"spiders",
"thunder and lightning",
"isolation",
"bacteria",
"falling",
"frogs",
"needls",
"books",
"ugliness",
"cancer",
"mirros",
"chemicals",
"happiness",
"bats",
"colours",
"clocks",
"time passing",
"food",
"closed spaces",
"cemetries",
"clowns",
"computers",
"dogs",
"demons",
"trees",
"dentists",
"houses",
"vomiting",
"crowds",
"insects",
"youth",
"horses",
"work",
"cold",
"marriage",
"bridges",
"aging",
"germs",
"balloons",
"public speaking",
"bad breath",
"sunlight",
"worms",
"blood",
"reptiles",
"666",
"travel",
"water",
"illness",
"fish",
"insects",
"buttons",
"butteflies",
"tornadoes or hurricanes",
"cooking",
"black",
"bees",
"being alone",
"mice",
"ants",
"death",
"new things",
"night",
"hospitals",
"numbers",
"darkness",
"weight gain",
"eyes",
"dreams",
"snakes",
"birds",
"smells",
"shellfish",
"everything",
"babies and children",
"medicine",
"ghosts",
"fear",
"loud sounds",
"beards",
"purple",
"flying",
"fire",
"radioactivity",
"roller coasters",
"trains",
"people",
"sleep",
"graves",
"technology",
"4",
"sea",
"dying",
"heat",
"poisons",
"injury",
"hair loss",
"13",
"needles",
"driving",
"yellow",
"foreigners",
]

print(phobia_list)
print(len(phobia_list))

print(fear_name_list)
print(len(fear_name_list))



print("{} is the fear of:".format(phobia_list[0]))